default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: abcd1234
  host: localhost

development:
  <<: *default
  database: tasktracker_development

test:
  <<: *default
  database: tasktracker_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  database: tasktracker_production
  username: postgres
  password: abcd1234
  host: localhost